version: 1.2.{build}
image: Visual Studio 2017
environment:
  api_key:
    secure: ypTf4wndO2Qd15JcOvncsnV8APna69YxVOvQLdkWrtguZUBa8TZlq47Qy+HMt7PT
branches:
  only:
  - master
skip_commits:
  message: /\[chore\]/
init:
  - git config --global core.autocrlf true
build_script:
- ps: >-
    dotnet restore

    $xmlPath = "$env:appveyor_build_folder\src\CodenameGenerator\CodenameGenerator.csproj"

    $xml = [xml](get-content $xmlPath)

    $propertyGroup = $xml.Project.PropertyGroup[0]

    $propertyGroup.Version = $env:appveyor_build_version

    $xml.Save($xmlPath)

    dotnet build -c Release
test_script:
- ps: >-
    cd tests/codenamegenerator.tests

    dotnet test -c Release --no-build
on_success:
- ps: >-
    if(!$env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
      nuget.exe setApiKey $env:api_key -source https://www.nuget.org
      nuget push "$env:appveyor_build_folder\src\CodenameGenerator\bin\Release\CodenameGenerator.$env:appveyor_build_version.nupkg" -source https://www.nuget.org
    }